# Generated by Django 4.2.7 on 2026-05-22 09:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmotionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Captured or uploaded face image', upload_to='face_emotions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp'])])),
                ('predicted_emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fear', 'Fear'), ('neutral', 'Neutral'), ('surprise', 'Surprise'), ('stress', 'Stress'), ('relaxed', 'Relaxed')], help_text='Predicted emotion from facial expression', max_length=20)),
                ('confidence_score', models.FloatField(help_text='Confidence score of the prediction (0-1)')),
                ('detection_method', models.CharField(choices=[('webcam', 'Webcam Capture'), ('upload', 'Image Upload'), ('realtime', 'Real-time Detection')], default='upload', help_text='Method used for detection', max_length=20)),
                ('face_detected', models.BooleanField(default=True, help_text='Whether a face was detected in the image')),
                ('face_coordinates', models.JSONField(blank=True, help_text='Face bounding box coordinates (x, y, width, height)', null=True)),
                ('all_probabilities', models.JSONField(blank=True, help_text='Probability scores for all emotions', null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Time taken to process in seconds', null=True)),
                ('prediction_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of prediction')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the prediction')),
                ('user', models.ForeignKey(help_text='User who made the prediction', on_delete=django.db.models.deletion.CASCADE, related_name='face_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Emotion Prediction',
                'verbose_name_plural': 'Face Emotion Predictions',
                'db_table': 'face_emotion_predictions',
                'ordering': ['-prediction_date'],
                'indexes': [models.Index(fields=['user', '-prediction_date'], name='face_emotio_user_id_aad98c_idx'), models.Index(fields=['predicted_emotion'], name='face_emotio_predict_38b70f_idx'), models.Index(fields=['detection_method'], name='face_emotio_detecti_af8c68_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaceDetectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(auto_now_add=True, help_text='Session start time')),
                ('session_end', models.DateTimeField(blank=True, help_text='Session end time', null=True)),
                ('total_frames', models.IntegerField(default=0, help_text='Total frames processed')),
                ('faces_detected', models.IntegerField(default=0, help_text='Number of frames with faces detected')),
                ('dominant_emotion', models.CharField(blank=True, help_text='Most frequent emotion in session', max_length=20)),
                ('emotion_distribution', models.JSONField(blank=True, help_text='Distribution of emotions throughout session', null=True)),
                ('average_confidence', models.FloatField(blank=True, help_text='Average confidence score', null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Session duration in seconds', null=True)),
                ('user', models.ForeignKey(help_text='User who started the session', on_delete=django.db.models.deletion.CASCADE, related_name='face_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Detection Session',
                'verbose_name_plural': 'Face Detection Sessions',
                'db_table': 'face_detection_sessions',
                'ordering': ['-session_start'],
                'indexes': [models.Index(fields=['user', '-session_start'], name='face_detect_user_id_1f92f4_idx')],
            },
        ),
    ]
