# Generated by Django 5.2.14 on 2026-05-25 11:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tip title', max_length=200)),
                ('content', models.TextField(help_text='Tip content/description')),
                ('emotion_category', models.CharField(choices=[('stress', 'Stress/Anxiety'), ('sadness', 'Sadness'), ('anger', 'Anger'), ('happy', 'Happy'), ('relaxed', 'Relaxed'), ('neutral', 'Neutral'), ('general', 'General Wellness')], help_text='Which emotion this tip is for', max_length=50)),
                ('tip_type', models.CharField(help_text='Type of tip (meditation, breathing, etc.)', max_length=50)),
                ('duration_minutes', models.IntegerField(default=5, help_text='Estimated time to complete (minutes)')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tip is currently active')),
                ('usage_count', models.IntegerField(default=0, help_text='How many times this tip has been recommended')),
                ('helpful_count', models.IntegerField(default=0, help_text='How many users found this helpful')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-helpful_count', 'title'],
                'indexes': [models.Index(fields=['emotion_category', 'is_active'], name='wellness_ch_emotion_ef616b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text="User's message or chatbot response")),
                ('is_user_message', models.BooleanField(default=True, help_text='True if message is from user, False if from chatbot')),
                ('emotion_context', models.CharField(blank=True, help_text='Emotion detected at time of message', max_length=50, null=True)),
                ('sentiment_score', models.FloatField(default=0.0, help_text='Sentiment score: -1 (negative) to 1 (positive)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, help_text='Chat session identifier', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='wellness_ch_user_id_bc1a3c_idx'), models.Index(fields=['session_id'], name='wellness_ch_session_4add83_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('trigger_emotion', models.CharField(help_text='Emotion that triggered the alert', max_length=50)),
                ('stress_score', models.FloatField(help_text='Stress score at time of alert')),
                ('alert_message', models.TextField(help_text='Alert message sent to user')),
                ('was_acknowledged', models.BooleanField(default=False, help_text='Whether user acknowledged the alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the alert was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how alert was resolved')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='wellness_ch_user_id_11cf65_idx'), models.Index(fields=['alert_level'], name='wellness_ch_alert_l_4935bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmotionalWellnessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(default=django.utils.timezone.now)),
                ('eeg_emotion', models.CharField(blank=True, help_text='Latest EEG emotion prediction', max_length=50, null=True)),
                ('face_emotion', models.CharField(blank=True, help_text='Latest facial emotion prediction', max_length=50, null=True)),
                ('combined_emotion', models.CharField(blank=True, help_text='Combined emotion analysis', max_length=50)),
                ('stress_level', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], default=3, help_text='Stress level (1-5)')),
                ('wellness_activities', models.JSONField(default=list, help_text='Wellness activities completed')),
                ('mood_rating', models.IntegerField(default=5, help_text='Self-reported mood (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, help_text='Personal notes')),
                ('chatbot_interactions', models.IntegerField(default=0, help_text='Number of chatbot interactions today')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-log_date'],
                'indexes': [models.Index(fields=['user', '-log_date'], name='wellness_ch_user_id_68beed_idx')],
                'unique_together': {('user', 'log_date')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('meditation', 'Meditation'), ('breathing', 'Breathing Exercise'), ('relaxation', 'Relaxation Technique'), ('motivation', 'Motivational Content'), ('music', 'Music Recommendation'), ('sleep', 'Sleep Suggestion'), ('productivity', 'Productivity Tip'), ('exercise', 'Physical Exercise'), ('social', 'Social Activity'), ('mindfulness', 'Mindfulness Practice'), ('emergency', 'Emergency Support')], max_length=50)),
                ('recommendation_text', models.TextField(help_text='The actual recommendation content')),
                ('emotion_trigger', models.CharField(help_text='Emotion that triggered this recommendation', max_length=50)),
                ('was_helpful', models.BooleanField(blank=True, default=None, help_text='User feedback on helpfulness', null=True)),
                ('was_completed', models.BooleanField(default=False, help_text='Whether user completed the recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_text', models.TextField(blank=True, help_text="User's feedback comments")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='wellness_ch_user_id_6afd01_idx'), models.Index(fields=['recommendation_type'], name='wellness_ch_recomme_0bd3c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='WellnessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=100, unique=True)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('dominant_emotion', models.CharField(blank=True, help_text='Most frequent emotion during session', max_length=50)),
                ('wellness_score', models.FloatField(default=50.0, help_text='Overall wellness score (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('recommendations_given', models.JSONField(default=list, help_text='List of recommendations provided')),
                ('session_summary', models.TextField(blank=True, help_text='Summary of the session')),
                ('message_count', models.IntegerField(default=0, help_text='Number of messages in session')),
                ('is_active', models.BooleanField(default=True, help_text='Whether session is currently active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_start'],
                'indexes': [models.Index(fields=['user', '-session_start'], name='wellness_ch_user_id_176645_idx'), models.Index(fields=['session_id'], name='wellness_ch_session_ee6eed_idx')],
            },
        ),
    ]
