# Generated by Django 4.2.7 on 2026-05-21 09:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EEGUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_path', models.FileField(help_text='Path to the uploaded EEG file', upload_to='eeg_uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'dat', 'edf', 'bdf'])])),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of upload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Processing status', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of the EEG data')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('processing_time', models.FloatField(blank=True, help_text='Time taken to process in seconds', null=True)),
            ],
            options={
                'verbose_name': 'EEG Upload',
                'verbose_name_plural': 'EEG Uploads',
                'db_table': 'eeg_uploads',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='PreprocessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(help_text='Name of preprocessing step', max_length=100)),
                ('step_description', models.TextField(help_text='Description of what was done')),
                ('parameters', models.JSONField(blank=True, help_text='Parameters used in this step', null=True)),
                ('execution_time', models.FloatField(help_text='Time taken for this step in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this step was executed')),
                ('success', models.BooleanField(default=True, help_text='Whether the step completed successfully')),
                ('error_message', models.TextField(blank=True, help_text='Error message if step failed')),
                ('upload', models.ForeignKey(help_text='Associated EEG upload', on_delete=django.db.models.deletion.CASCADE, related_name='preprocessing_logs', to='eeg_processing.eegupload')),
            ],
            options={
                'verbose_name': 'Preprocessing Log',
                'verbose_name_plural': 'Preprocessing Logs',
                'db_table': 'preprocessing_logs',
                'ordering': ['upload', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmotionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('relaxed', 'Relaxed'), ('stressed', 'Stressed'), ('excited', 'Excited')], help_text='Predicted emotion', max_length=50)),
                ('confidence_score', models.FloatField(help_text='Confidence score of the prediction (0-1)')),
                ('model_used', models.CharField(choices=[('cnn', 'CNN'), ('lstm', 'LSTM'), ('hybrid', 'Hybrid')], help_text='ML model used for prediction', max_length=50)),
                ('prediction_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of prediction')),
                ('valence', models.FloatField(blank=True, help_text='Valence score (1-9 scale)', null=True)),
                ('arousal', models.FloatField(blank=True, help_text='Arousal score (1-9 scale)', null=True)),
                ('dominance', models.FloatField(blank=True, help_text='Dominance score (1-9 scale)', null=True)),
                ('raw_predictions', models.JSONField(blank=True, help_text='Raw prediction probabilities for all emotions', null=True)),
                ('upload', models.ForeignKey(help_text='Associated EEG upload', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='eeg_processing.eegupload')),
            ],
            options={
                'verbose_name': 'Emotion Prediction',
                'verbose_name_plural': 'Emotion Predictions',
                'db_table': 'emotion_predictions',
                'ordering': ['-prediction_date'],
            },
        ),
    ]
