# Generated by Django 4.2.7 on 2026-05-21 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eeg_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionprediction',
            name='user',
            field=models.ForeignKey(help_text='User who requested the prediction', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eegupload',
            name='user',
            field=models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='eeg_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emotionprediction',
            index=models.Index(fields=['user', '-prediction_date'], name='emotion_pre_user_id_f34f19_idx'),
        ),
        migrations.AddIndex(
            model_name='emotionprediction',
            index=models.Index(fields=['predicted_emotion'], name='emotion_pre_predict_2c59c8_idx'),
        ),
        migrations.AddIndex(
            model_name='emotionprediction',
            index=models.Index(fields=['upload'], name='emotion_pre_upload__635eef_idx'),
        ),
        migrations.AddIndex(
            model_name='eegupload',
            index=models.Index(fields=['user', '-upload_date'], name='eeg_uploads_user_id_59cbf5_idx'),
        ),
        migrations.AddIndex(
            model_name='eegupload',
            index=models.Index(fields=['status'], name='eeg_uploads_status_1d5f2f_idx'),
        ),
    ]
