# Generated by Django 4.2.7 on 2026-05-21 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField(help_text='Detailed recommendation text')),
                ('recommendation_type', models.CharField(choices=[('activity', 'Activity'), ('meditation', 'Meditation'), ('music', 'Music'), ('exercise', 'Exercise'), ('therapy', 'Therapy'), ('breathing', 'Breathing Exercise'), ('social', 'Social Activity'), ('relaxation', 'Relaxation Technique')], help_text='Type of recommendation', max_length=50)),
                ('priority', models.IntegerField(default=1, help_text='Priority level (1=low, 5=high)')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='When recommendation was created')),
                ('is_viewed', models.BooleanField(default=False, help_text='Whether user has viewed this recommendation')),
                ('is_helpful', models.BooleanField(blank=True, help_text='User feedback on helpfulness', null=True)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'db_table': 'recommendations',
                'ordering': ['-priority', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('relaxed', 'Relaxed'), ('stressed', 'Stressed'), ('excited', 'Excited')], help_text='Target emotion', max_length=50)),
                ('recommendation_type', models.CharField(choices=[('activity', 'Activity'), ('meditation', 'Meditation'), ('music', 'Music'), ('exercise', 'Exercise'), ('therapy', 'Therapy'), ('breathing', 'Breathing Exercise'), ('social', 'Social Activity'), ('relaxation', 'Relaxation Technique')], help_text='Type of recommendation', max_length=50)),
                ('title', models.CharField(help_text='Recommendation title', max_length=200)),
                ('content', models.TextField(help_text='Recommendation content template')),
                ('priority', models.IntegerField(default=1, help_text='Default priority level')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recommendation Template',
                'verbose_name_plural': 'Recommendation Templates',
                'db_table': 'recommendation_templates',
                'ordering': ['emotion', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Not Helpful'), (2, 'Slightly Helpful'), (3, 'Moderately Helpful'), (4, 'Very Helpful'), (5, 'Extremely Helpful')], help_text='User rating')),
                ('comment', models.TextField(blank=True, help_text='Optional feedback comment')),
                ('followed', models.BooleanField(default=False, help_text='Whether user followed the recommendation')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='When feedback was provided')),
                ('recommendation', models.ForeignKey(help_text='Associated recommendation', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommendations.recommendation')),
            ],
            options={
                'verbose_name': 'User Recommendation Feedback',
                'verbose_name_plural': 'User Recommendation Feedback',
                'db_table': 'user_recommendation_feedback',
                'ordering': ['-created_date'],
            },
        ),
    ]
