# Generated by Django 4.2.7 on 2026-05-21 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eeg_processing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecommendationfeedback',
            name='user',
            field=models.ForeignKey(help_text='User providing feedback', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='prediction',
            field=models.ForeignKey(help_text='Associated emotion prediction', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='eeg_processing.emotionprediction'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(help_text='User receiving the recommendation', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userrecommendationfeedback',
            unique_together={('recommendation', 'user')},
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', '-created_date'], name='recommendat_user_id_f20480_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['prediction'], name='recommendat_predict_52cdff_idx'),
        ),
    ]
