# Generated by Django 4.2.7 on 2026-05-21 09:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEvaluationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.FloatField(help_text='Precision score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('recall', models.FloatField(help_text='Recall score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('f1_score', models.FloatField(help_text='F1 score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confusion_matrix', models.JSONField(help_text='Confusion matrix data')),
                ('classification_report', models.JSONField(help_text='Detailed classification report')),
                ('roc_auc_score', models.FloatField(blank=True, help_text='ROC AUC score', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('per_class_accuracy', models.JSONField(blank=True, help_text='Accuracy per emotion class', null=True)),
            ],
            options={
                'verbose_name': 'Model Evaluation Metrics',
                'verbose_name_plural': 'Model Evaluation Metrics',
                'db_table': 'model_evaluation_metrics',
            },
        ),
        migrations.CreateModel(
            name='ModelTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Name of the trained model', max_length=100)),
                ('model_type', models.CharField(choices=[('cnn', 'CNN'), ('lstm', 'LSTM'), ('hybrid', 'Hybrid')], help_text='Type of ML model', max_length=50)),
                ('accuracy', models.FloatField(help_text='Model accuracy percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('loss', models.FloatField(help_text='Training loss value')),
                ('val_accuracy', models.FloatField(blank=True, help_text='Validation accuracy percentage', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('val_loss', models.FloatField(blank=True, help_text='Validation loss value', null=True)),
                ('epochs', models.IntegerField(help_text='Number of training epochs')),
                ('batch_size', models.IntegerField(default=32, help_text='Batch size used during training')),
                ('learning_rate', models.FloatField(default=0.001, help_text='Learning rate used')),
                ('training_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of training')),
                ('training_duration', models.FloatField(blank=True, help_text='Training duration in seconds', null=True)),
                ('parameters', models.JSONField(help_text='Model hyperparameters and configuration')),
                ('model_path', models.CharField(help_text='Path to saved model file', max_length=500)),
                ('dataset_info', models.JSONField(blank=True, help_text='Information about training dataset', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about training')),
            ],
            options={
                'verbose_name': 'Model Training Log',
                'verbose_name_plural': 'Model Training Logs',
                'db_table': 'model_training_logs',
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('cnn', 'CNN'), ('lstm', 'LSTM'), ('hybrid', 'Hybrid')], help_text='Type of ML model', max_length=50)),
                ('version', models.CharField(help_text='Version number (e.g., 1.0.0)', max_length=20)),
                ('status', models.CharField(choices=[('development', 'Development'), ('testing', 'Testing'), ('production', 'Production'), ('deprecated', 'Deprecated')], default='development', help_text='Current status of this version', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this version is currently active')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='When this version was created')),
                ('deployed_date', models.DateTimeField(blank=True, help_text='When this version was deployed to production', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of changes in this version')),
                ('training_log', models.ForeignKey(blank=True, help_text='Associated training log', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='ml_models.modeltraininglog')),
            ],
            options={
                'verbose_name': 'Model Version',
                'verbose_name_plural': 'Model Versions',
                'db_table': 'model_versions',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddIndex(
            model_name='modeltraininglog',
            index=models.Index(fields=['model_type', '-training_date'], name='model_train_model_t_de7279_idx'),
        ),
        migrations.AddIndex(
            model_name='modeltraininglog',
            index=models.Index(fields=['-accuracy'], name='model_train_accurac_95d523_idx'),
        ),
        migrations.AddField(
            model_name='modelevaluationmetrics',
            name='training_log',
            field=models.OneToOneField(help_text='Associated training log', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_metrics', to='ml_models.modeltraininglog'),
        ),
        migrations.AlterUniqueTogether(
            name='modelversion',
            unique_together={('model_type', 'version')},
        ),
    ]
